### ISSUE TITLE
ITS A ME FATRIO

### ISSUE THREAD

**Issue by thefatos** [dounasiudb/boncau#1]
heroin good jk what am i doing with life w h a t

**Comment by dounasiudb** [comment]
wsc modmail opensource when

**Comment by thefatos** [comment]
https://github.com/kyb3r/modmail/ there

**Comment by thefatos** [comment]
i host it now lol

**Comment by thefatos** [comment]
and ive been stalking your github account for 4 months

**Comment by thefatos** [comment]
fun fact: steam has a fucking game named **SEX WITH HITLER** i am not lying

**Comment by dounasiudb** [comment]
> and ive been stalking your github account for 4 months

so since my fucking discor daccount been gone you've been fucking with my github account yay
